name: Validate

on:
  pull_request:
    branches: [ develop ]

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/client/node_modules
            **/api/node_modules
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install

      - name: Lint Client
        run: |
          cd client
          yarn lint

      - name: Lint API
        run: |
          cd api
          yarn lint

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/client/node_modules
            **/api/node_modules
            ${{ github.workspace }}/client/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install

      - name: Validate API Build
        run: |
          cd api
          yarn validate-schema

      - name: Validate Client Build
        run: |
          cd client
          yarn build
